// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Rift.Data;

namespace Rift.Migrations
{
    [DbContext(typeof(RiftContext))]
    [Migration("20190407221643_Move")]
    partial class Move
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RiftDatabaseConverter.Data.Models.RiftCooldowns", b =>
                {
                    b.Property<decimal>("UserId")
                        .HasConversion(new ValueConverter<decimal, decimal>(v => default(decimal), v => default(decimal), new ConverterMappingHints(precision: 20, scale: 0)));

                    b.Property<DateTime>("BotRespectTime");

                    b.Property<DateTime>("DoubleExpTime");

                    b.Property<DateTime>("LastAttackTime");

                    b.Property<DateTime>("LastBeingAttackedTime");

                    b.Property<DateTime>("LastBragTime");

                    b.Property<DateTime>("LastDailyChestTime");

                    b.Property<DateTime>("LastGiftTime");

                    b.Property<DateTime>("LastLolAccountUpdateTime");

                    b.Property<DateTime>("LastStoreTime");

                    b.HasKey("UserId");

                    b.ToTable("Cooldowns");
                });

            modelBuilder.Entity("RiftDatabaseConverter.Data.Models.RiftInventory", b =>
                {
                    b.Property<decimal>("UserId")
                        .HasConversion(new ValueConverter<decimal, decimal>(v => default(decimal), v => default(decimal), new ConverterMappingHints(precision: 20, scale: 0)));

                    b.Property<long>("Capsules");

                    b.Property<long>("Chests");

                    b.Property<long>("Coins");

                    b.Property<long>("PowerupsBotRespect");

                    b.Property<long>("PowerupsDoubleExp");

                    b.Property<long>("RareTickets");

                    b.Property<long>("Spheres");

                    b.Property<long>("Tokens");

                    b.Property<long>("UsualTickets");

                    b.HasKey("UserId");

                    b.ToTable("Inventory");
                });

            modelBuilder.Entity("RiftDatabaseConverter.Data.Models.RiftLolData", b =>
                {
                    b.Property<decimal>("UserId")
                        .HasConversion(new ValueConverter<decimal, decimal>(v => default(decimal), v => default(decimal), new ConverterMappingHints(precision: 20, scale: 0)));

                    b.Property<string>("AccountId");

                    b.Property<string>("PlayerUUID");

                    b.Property<string>("SummonerId");

                    b.Property<string>("SummonerName");

                    b.Property<string>("SummonerRegion");

                    b.HasKey("UserId");

                    b.ToTable("LolData");
                });

            modelBuilder.Entity("RiftDatabaseConverter.Data.Models.RiftPendingUser", b =>
                {
                    b.Property<decimal>("UserId")
                        .HasConversion(new ValueConverter<decimal, decimal>(v => default(decimal), v => default(decimal), new ConverterMappingHints(precision: 20, scale: 0)));

                    b.Property<string>("AccountId");

                    b.Property<string>("ConfirmationCode");

                    b.Property<DateTime>("ExpirationTime");

                    b.Property<string>("PlayerUUID");

                    b.Property<string>("Region");

                    b.Property<string>("SummonedId");

                    b.HasKey("UserId");

                    b.ToTable("PendingUsers");
                });

            modelBuilder.Entity("RiftDatabaseConverter.Data.Models.RiftStatistics", b =>
                {
                    b.Property<decimal>("UserId")
                        .HasConversion(new ValueConverter<decimal, decimal>(v => default(decimal), v => default(decimal), new ConverterMappingHints(precision: 20, scale: 0)));

                    b.Property<long>("AttacksDone");

                    b.Property<long>("AttacksReceived");

                    b.Property<long>("BragTotal");

                    b.Property<long>("CapsuleEarnedTotal");

                    b.Property<long>("CapsuleOpenedTotal");

                    b.Property<long>("ChestsEarnedTotal");

                    b.Property<long>("ChestsOpenedTotal");

                    b.Property<long>("CoinsEarnedTotal");

                    b.Property<long>("CoinsSpentTotal");

                    b.Property<long>("GiftsReceived");

                    b.Property<long>("GiftsSent");

                    b.Property<long>("MessagesSentTotal");

                    b.Property<long>("PurchasedItemsTotal");

                    b.Property<long>("SphereEarnedTotal");

                    b.Property<long>("SphereOpenedTotal");

                    b.Property<long>("TokensEarnedTotal");

                    b.Property<long>("TokensSpentTotal");

                    b.HasKey("UserId");

                    b.ToTable("Statistics");
                });

            modelBuilder.Entity("RiftDatabaseConverter.Data.Models.RiftStreamer", b =>
                {
                    b.Property<decimal>("UserId")
                        .HasConversion(new ValueConverter<decimal, decimal>(v => default(decimal), v => default(decimal), new ConverterMappingHints(precision: 20, scale: 0)));

                    b.Property<string>("PictureUrl");

                    b.Property<string>("StreamUrl");

                    b.HasKey("UserId");

                    b.ToTable("Streamers");
                });

            modelBuilder.Entity("RiftDatabaseConverter.Data.Models.RiftTempRole", b =>
                {
                    b.Property<decimal>("UserId")
                        .HasConversion(new ValueConverter<decimal, decimal>(v => default(decimal), v => default(decimal), new ConverterMappingHints(precision: 20, scale: 0)));

                    b.Property<decimal>("RoleId")
                        .HasConversion(new ValueConverter<decimal, decimal>(v => default(decimal), v => default(decimal), new ConverterMappingHints(precision: 20, scale: 0)));

                    b.Property<DateTime>("ExpirationTime");

                    b.Property<string>("ObtainedFrom");

                    b.Property<DateTime>("ObtainedTime");

                    b.HasKey("UserId", "RoleId");

                    b.ToTable("TempRoles");
                });

            modelBuilder.Entity("RiftDatabaseConverter.Data.Models.RiftUser", b =>
                {
                    b.Property<decimal>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasConversion(new ValueConverter<decimal, decimal>(v => default(decimal), v => default(decimal), new ConverterMappingHints(precision: 20, scale: 0)));

                    b.Property<decimal>("Donate");

                    b.Property<long>("Experience");

                    b.Property<long>("Level");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RiftDatabaseConverter.Data.Models.ScheduledEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("DayId");

                    b.Property<int>("EventId");

                    b.Property<int>("Hour");

                    b.Property<int>("Minute");

                    b.HasKey("Id");

                    b.ToTable("ScheduledEvents");
                });

            modelBuilder.Entity("RiftDatabaseConverter.Data.Models.RiftCooldowns", b =>
                {
                    b.HasOne("RiftDatabaseConverter.Data.Models.RiftUser", "User")
                        .WithOne("Cooldowns")
                        .HasForeignKey("RiftDatabaseConverter.Data.Models.RiftCooldowns", "UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("RiftDatabaseConverter.Data.Models.RiftInventory", b =>
                {
                    b.HasOne("RiftDatabaseConverter.Data.Models.RiftUser", "User")
                        .WithOne("Inventory")
                        .HasForeignKey("RiftDatabaseConverter.Data.Models.RiftInventory", "UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("RiftDatabaseConverter.Data.Models.RiftLolData", b =>
                {
                    b.HasOne("RiftDatabaseConverter.Data.Models.RiftUser", "User")
                        .WithOne("LolData")
                        .HasForeignKey("RiftDatabaseConverter.Data.Models.RiftLolData", "UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("RiftDatabaseConverter.Data.Models.RiftPendingUser", b =>
                {
                    b.HasOne("RiftDatabaseConverter.Data.Models.RiftUser", "User")
                        .WithOne("PendingUser")
                        .HasForeignKey("RiftDatabaseConverter.Data.Models.RiftPendingUser", "UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("RiftDatabaseConverter.Data.Models.RiftStatistics", b =>
                {
                    b.HasOne("RiftDatabaseConverter.Data.Models.RiftUser", "User")
                        .WithOne("Statistics")
                        .HasForeignKey("RiftDatabaseConverter.Data.Models.RiftStatistics", "UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("RiftDatabaseConverter.Data.Models.RiftStreamer", b =>
                {
                    b.HasOne("RiftDatabaseConverter.Data.Models.RiftUser", "User")
                        .WithOne("Streamers")
                        .HasForeignKey("RiftDatabaseConverter.Data.Models.RiftStreamer", "UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("RiftDatabaseConverter.Data.Models.RiftTempRole", b =>
                {
                    b.HasOne("RiftDatabaseConverter.Data.Models.RiftUser", "User")
                        .WithMany("TempRoles")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_RiftTempRoles_Users_UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
