namespace Rift.Configuration
{
    public class Emote
    {
        public string Coin { get; set; }
        public string CoinUrl { get; set; }
        public string Token { get; set; }
        public string LevelUp { get; set; }
        public string LevelUpUrl { get; set; }
        public string Chest { get; set; }
        public string ChestUrl { get; set; }
        public string Capsule { get; set; }
        public string CapsuleUrl { get; set; }
        public string Donate { get; set; }
        public string DonateUrl { get; set; }
        public string ExMark { get; set; }
        public string ExMarkUrl { get; set; }
        public string QuestionMark { get; set; }
        public string QuestionMarkUrl { get; set; }
        public string Gifts { get; set; }
        public string GiftsUrl { get; set; }
        public string Verify { get; set; }
        public string VerifyUrl { get; set; }
        public string Store { get; set; }
        public string StoreUrl { get; set; }
        public string Giveaway { get; set; }
        public string GiveawayUrl { get; set; }
        public string Attack { get; set; }
        public string AttackUrl { get; set; }
        public string Smite { get; set; }
        public string Summoner { get; set; }
        public string Twitch { get; set; }
        public string Youtube { get; set; }
        public string LolRu { get; set; }
        public string RP { get; set; }
        public string Rewards { get; set; }
        public string Member { get; set; }
        public string PouchCoins { get; set; }
        public string PouchTokens { get; set; }
        public string Yasuo { get; set; }
        public string Profile { get; set; }
        public string Legendary { get; set; }
        public string Absolute { get; set; }
        public string Keeper { get; set; }
        public string Thonk { get; set; }
        public string StoreChest { get; set; }
        public string StoreArcade { get; set; }
        public string StoreBotRespect { get; set; }
        public string StoreJusticars { get; set; }
        public string StoreParty { get; set; }
        public string StoreWorldbreakers { get; set; }
        public string StoreVictorious { get; set; }
        public string StoreDebonair { get; set; }
        public string StoreThunderlords { get; set; }
        public string StoreArclight { get; set; }
        public string StoreDarkStar { get; set; }
        public string StoreBloodMoon { get; set; }
        public string StoreVandals { get; set; }
        public string RankIron { get; set; }
        public string RankBronze { get; set; }
        public string RankSilver { get; set; }
        public string RankGold { get; set; }
        public string RankPlatinum { get; set; }
        public string RankDiamond { get; set; }
        public string RankMaster { get; set; }
        public string RankGrandmaster { get; set; }
        public string RankChallenger { get; set; }
        public string Baron { get; set; }
        public string BaronUrl { get; set; }
        public string Drake { get; set; }
        public string DrakeUrl { get; set; }
        public string Wolves { get; set; }
        public string WolvesUrl { get; set; }
        public string Razorfins { get; set; }
        public string RazorfinsUrl { get; set; }
        public string Gromp { get; set; }
        public string GrompUrl { get; set; }
        public string Achievement { get; set; }
        public string AchievementUrl { get; set; }
        public string Daily { get; set; }
        public string DailyUrl { get; set; }
        public string Id { get; set; }
        public string Forms { get; set; }
        public string FormsUrl { get; set; }
        public string StoreMagicSet { get; set; }
        public string StoreMagicSetUrl { get; set; }
        public string Vk { get; set; }
        public string VkUrl { get; set; }
        public string Krug { get; set; }
        public string KrugUrl { get; set; }
        public string DonateGift { get; set; }
        public string DonateDiamond { get; set; }
        public string Sphere { get; set; }
        public string SphereUrl { get; set; }
        public string PowerupDoubleExperience { get; set; }
        public string PowerupDoubleExperienceUrl { get; set; }
        public string PowerupAttack { get; set; }
        public string PowerupAttackUrl { get; set; }
        public string BotRespect { get; set; }
        public string BotRespectUrl { get; set; }
        public string RedBuff { get; set; }
        public string RedBuffUrl { get; set; }
        public string BlueBuff { get; set; }
        public string BlueBuffUrl { get; set; }
        public string Pogchamp { get; set; }
        public string Oh { get; set; }
        public string ChestLol { get; set; }
        public string ChestLolUrl { get; set; }
        public string RareTickets { get; set; }
        public string RareTicketsUrl { get; set; }
        public string UsualTickets { get; set; }
        public string UsualTicketsUrl { get; set; }
        public string Roles { get; set; }
        public string RolesUrl { get; set; }
        public string Voice { get; set; }
        public string VoiceUrl { get; set; }
        public string Experience { get; set; }
        public string ExperienceUrl { get; set; }
        public string MarkedAchievement { get; set; }
        public string MarkedAchievementUrl { get; set; }
        public string UnmarkedAchievement { get; set; }
        public string UnmarkedAchievementUrl { get; set; }
        public string Lol { get; set; }
        public string LolUrl { get; set; }
        public string Inventory { get; set; }
        public string InventoryUrl { get; set; }
        public string Chosen { get; set; }
        public string ChosenUrl { get; set; }
        public string DarkStar { get; set; }
        public string DarkStarUrl { get; set; }
        public string Arcade { get; set; }
        public string ArcadeUrl { get; set; }
        public string Debonairs { get; set; }
        public string DebonairsUrl { get; set; }
        public string StarGuardians { get; set; }
        public string StarGuardiansUrl { get; set; }
        public string BloodMoon { get; set; }
        public string BloodMoonUrl { get; set; }
        public string Hextech { get; set; }
        public string HextechUrl { get; set; }
        public string Party { get; set; }
        public string PartyUrl { get; set; }
        public string Mythic { get; set; }
        public string MythicUrl { get; set; }
        public string Victorious { get; set; }
        public string VictoriousUrl { get; set; }
        public string Honor { get; set; }
        public string HonorUrl { get; set; }
        public string BlockedHonor { get; set; }
        public string BlockedHonorUrl { get; set; }
        public string Invisible { get; set; }
        public string InvisibleUrl { get; set; }
        public string Ghost { get; set; }
        public string Flash { get; set; }
        public string Heal { get; set; }
        public string Ignite { get; set; }
        public string Barrier { get; set; }
        public string Ward { get; set; }
    }
}
